# Generated by Django 3.1.7 on 2021-03-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(verbose_name='board published')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('contents', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='board published')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rollingPaper.board')),
            ],
        ),
    ]
