# Generated by Django 3.1.7 on 2021-03-18 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board_name', models.CharField(max_length=40)),
                ('board_pw', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('contents', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rollingPaper.board')),
            ],
        ),
    ]
